/**
 * v1.0.92 — Copy PC Specs (Settings → Performance → Your Hardware).
 *
 * Collects the user's real hardware + system + launcher context into a
 * clean, privacy-safe plain-text block and copies it to the clipboard.
 *
 * PRIVACY: never includes username, emails, tokens, IP/MAC addresses,
 * serials, product keys or any PII — only technical specifications.
 */
import { clipboard } from 'electron'
import { appVersion } from '../paths'
import { detectHardware } from '../perf/hardware'
import { detectJavaRuntimes } from '../minecraft/java'
import type { HardwareProfile, Profile } from '@shared/types'

function fmt(n: number | null | undefined, suffix = ''): string {
  if (n === null || n === undefined || Number.isNaN(n)) return 'Unknown'
  return `${n}${suffix}`
}

function orUnknown(v: string | null | undefined): string {
  return v && v.trim() ? v : 'Unknown'
}

function buildJava(profile?: Profile | null): { version: string; vendor: string; arch: string } {
  let version = 'Unknown'
  let vendor = 'Not detected'
  const arch = process.arch === 'x64' ? '64-bit' : process.arch
  try {
    const runtimes = detectJavaRuntimes(true)
    if (runtimes.length > 0) {
      version = runtimes[0].version || `Java ${runtimes[0].major}`
      vendor = orUnknown(runtimes[0].vendor)
    }
  } catch {
    /* non-fatal */
  }
  return { version, vendor, arch }
}

/** Async variant that waits for the real hardware probe (cached). */
export async function buildSpecsTextAsync(opts: { minimal?: boolean; profile?: Profile | null } = {}): Promise<string> {
  const minimal = opts.minimal ?? false
  const profile = opts.profile ?? null
  const hw = await detectHardware(false)

  const java = buildJava(profile)
  const lines: string[] = []

  if (minimal) {
    lines.push('REIMAGINED MINIMAL PC SPECS')
    lines.push('')
    lines.push(`CPU: ${hw?.cpu.model ? orUnknown(hw.cpu.model.split('@')[0].trim()) : 'Unknown'}`)
    lines.push(`GPU: ${hw?.gpu && hw.gpu.length ? hw.gpu.map((g) => orUnknown(g.name)).join(' + ') : 'Unknown'}`)
    lines.push(`RAM: ${fmt(hw?.memory.totalGB, ' GB')}`)
    lines.push(`OS: ${orUnknown(hw?.os)}`)
    lines.push(`Java: ${java.version}`)
    lines.push(`Minecraft: ${profile?.minecraftVersion ?? 'N/A'}`)
    lines.push(`Loader: ${profile?.loader?.type ? profile.loader.type.charAt(0).toUpperCase() + profile.loader.type.slice(1) : 'N/A'}`)
    lines.push('')
    lines.push(`Reimagined Launcher: v${appVersion}`)
    return lines.join('\n')
  }

  lines.push('REIMAGINED PC SPECS')
  lines.push('')
  lines.push('## CPU')
  lines.push(`CPU: ${orUnknown(hw?.cpu.model)}`)
  lines.push(`Cores: ${fmt(hw?.cpu.cores)}`)
  lines.push(`Threads: ${fmt(hw?.cpu.threads)}`)
  lines.push(`Architecture: ${process.arch === 'x64' ? 'x64' : process.arch}`)
  lines.push(`Base Clock: ${fmt(hw?.cpu.speedGHz, ' GHz')}`)
  if (hw?.cpu.cache && hw.cpu.cache !== 'n/a') lines.push(`Cache: ${orUnknown(hw.cpu.cache)}`)
  lines.push('')
  lines.push('## GPU')
  if (hw?.gpu && hw.gpu.length > 0) {
    for (const g of hw.gpu) {
      lines.push(`GPU: ${orUnknown(g.name)}${g.integrated ? ' (Integrated)' : ' (Dedicated)'}`)
      lines.push(`VRAM: ${fmt(g.vramGB, ' GB')}`)
      if (g.driverVersion) lines.push(`Driver: ${orUnknown(g.driverVersion)}`)
    }
  } else {
    lines.push('GPU: Unknown')
  }
  lines.push('')
  lines.push('## MEMORY')
  lines.push(`RAM: ${fmt(hw?.memory.totalGB, ' GB')}`)
  lines.push(`Speed: ${fmt(hw?.memory.speedMHz, ' MHz')}`)
  lines.push('')
  lines.push('## DISPLAY')
  lines.push(`Resolution: ${orUnknown(hw?.display.resolution)}`)
  lines.push(`Refresh Rate: ${fmt(hw?.display.refreshHz, ' Hz')}`)
  lines.push(`Displays: ${hw?.gpu && hw.gpu.length ? hw.gpu.length : 'Unknown'}`)
  lines.push('')
  lines.push('## STORAGE')
  lines.push(`Main Drive: ${orUnknown(hw?.storage.drive)}`)
  lines.push(`Capacity: ${fmt(hw?.storage.totalGB, ' GB')}`)
  lines.push(`Free Space: ${fmt(hw?.storage.freeGB, ' GB')}`)
  lines.push(`Used Space: ${fmt(hw?.storage.usedGB, ' GB')}`)
  lines.push('')
  lines.push('## JAVA')
  lines.push(`Java: ${java.version}`)
  lines.push(`Vendor: ${java.vendor}`)
  lines.push(`Architecture: ${java.arch}`)
  lines.push('')
  lines.push('## OPERATING SYSTEM')
  lines.push(`OS: ${orUnknown(hw?.os)}`)
  lines.push(`Architecture: ${process.arch === 'x64' ? '64-bit' : process.arch}`)
  lines.push('')
  lines.push('## REIMAGINED')
  lines.push(`Launcher Version: v${appVersion}`)
  lines.push(`Minecraft Version: ${profile?.minecraftVersion ?? 'N/A'}`)
  lines.push(`Loader: ${profile?.loader?.type ? profile.loader.type.charAt(0).toUpperCase() + profile.loader.type.slice(1) : 'N/A'}`)
  lines.push(`Instance: ${profile?.name ?? 'N/A'}`)
  lines.push('')
  lines.push('(Generated by Reimagined Launcher — technical specifications only, no personal data.)')
  return lines.join('\n')
}

/** Copy the specs block to the system clipboard. */
export async function copySpecsToClipboard(opts: { minimal?: boolean; profile?: Profile | null } = {}): Promise<string> {
  const text = await buildSpecsTextAsync(opts)
  clipboard.writeText(text)
  return text
}

