// Reimagined Launcher — secure CurseForge proxy (Change 5, v1.0.36, fixed v1.0.38).
//
// The CurseForge API v3 key lives ONLY here as the CF_API_KEY environment
// variable — it is never shipped inside the launcher and never committed to
// the repository. The launcher talks to this proxy over HTTPS; the proxy
// talks to api.curseforge.com with the key.
//
// Deploy anywhere that runs Node (Render, Railway, Fly.io, a VPS...):
//   CF_API_KEY=your_key_here node server.js        (PORT defaults to 8787)
// Then paste `https://your-proxy-host/` into the launcher at
// Settings -> Advanced -> CurseForge proxy URL.
const http = require('http')
const https = require('https')
const fs = require('fs')
const path = require('path')

const PORT = process.env.PORT || 8787
const CF_API_KEY = process.env.CF_API_KEY
if (!CF_API_KEY) {
  console.error('[cf-proxy] Missing CF_API_KEY env var — set it to your CurseForge API v3 key.')
  process.exit(1)
}

const CF_BASE = 'https://api.curseforge.com/v1'
const UA = 'ReimaginedLauncher/1.0.38 (Minecraft launcher)'

// Whitelisted routes. The launcher (src/main/mods/curseforge.ts) forwards the
// raw CurseForge API path under /api/cf/mods/... — those are the primary
// routes. The short aliases (/search, /project, /files, /changelog, /file)
// are kept for quick manual testing in a browser. Query strings are forwarded
// where CurseForge needs them (/mods/search, /mods/:id/files).
const ROUTES = [
  // --- launcher paths (what the launcher actually sends) ---
  { re: /^\/api\/cf\/mods\/search$/,                 cf: (u) => '/mods/search' + u.search },
  // v1.0.50 — category tree for the Browse sidebar (gameId=432 filter added
  // by the launcher). Old proxies that lack this route make the launcher
  // degrade to deriving categories from search hits instead of erroring.
  { re: /^\/api\/cf\/categories$/,                   cf: (u) => '/categories' + u.search },
  { re: /^\/api\/cf\/mods\/(\d+)$/,                  cf: (u, m) => `/mods/${m[1]}` },
  { re: /^\/api\/cf\/mods\/(\d+)\/files$/,           cf: (u, m) => `/mods/${m[1]}/files` + u.search },
  { re: /^\/api\/cf\/mods\/(\d+)\/files\/(\d+)\/changelog$/, cf: (u, m) => `/mods/${m[1]}/files/${m[2]}/changelog` },
  { re: /^\/api\/cf\/mods\/(\d+)\/files\/(\d+)$/,    cf: (u, m) => `/mods/${m[1]}/files/${m[2]}` },
  // --- short aliases for manual browser testing ---
  { re: /^\/api\/cf\/search$/,                       cf: (u) => '/mods/search' + u.search },
  { re: /^\/api\/cf\/project\/(\d+)$/,               cf: (u, m) => `/mods/${m[1]}` },
  { re: /^\/api\/cf\/files\/(\d+)$/,                 cf: (u, m) => `/mods/${m[1]}/files` + u.search },
  { re: /^\/api\/cf\/changelog\/(\d+)\/(\d+)$/,      cf: (u, m) => `/mods/${m[1]}/files/${m[2]}/changelog` },
  { re: /^\/api\/cf\/file\/(\d+)\/(\d+)$/,           cf: (u, m) => `/mods/${m[1]}/files/${m[2]}` }
]

function proxy(u, m) {
  return new Promise((resolve) => {
    const cfPath = ROUTES.find((r) => r.re.test(u.pathname))
    if (!cfPath) return resolve({ status: 404, body: { error: 'Not found' } })
    const target = CF_BASE + cfPath.cf(u, cfPath.re.exec(u.pathname))
    const req = https.get(target, {
      headers: { 'x-api-key': CF_API_KEY, Accept: 'application/json', 'User-Agent': UA }
    }, (res) => {
      let raw = ''
      res.on('data', (d) => { raw += d })
      res.on('end', () => {
        let body = raw
        try { body = JSON.parse(raw) } catch { /* pass raw */ }
        resolve({ status: res.statusCode, body })
      })
    })
    req.on('error', () => resolve({ status: 502, body: { error: 'Upstream unreachable' } }))
    // v1.0.51 — generous upstream timeout: cold-started proxies can take
    // ~40 s to wake; 25 s used to abort on the first request after idle.
    req.setTimeout(45000, () => { req.destroy(); resolve({ status: 504, body: { error: 'Upstream timeout' } }) })
  })
}

/* ==========================================================================
   Share codes (v1.0.81) — online profile share.

   A share code generated by the launcher is PUBLISHED here (snapshot + 7-day
   expiry) so it resolves from ANY launcher, not just the machine that made
   it. Storage is an in-memory map persisted to share-store.json (survives
   restarts on the same instance; a redeploy simply starts empty — codes are
   short-lived anyway). Requests are cheap and rate-limited per IP so the free
   tier can't be hammered.
   ========================================================================== */
const SHARE_TTL_MS = 7 * 24 * 60 * 60 * 1000
const MAX_SNAPSHOT_BYTES = 2 * 1024 * 1024
const SHARE_STORE_FILE = path.join(__dirname, 'share-store.json')

let shareStore = {}
let shareStoreLoaded = false
function loadShareStore() {
  if (shareStoreLoaded) return
  shareStoreLoaded = true
  try {
    shareStore = JSON.parse(fs.readFileSync(SHARE_STORE_FILE, 'utf8'))
  } catch {
    shareStore = {}
  }
}
function saveShareStore() {
  try {
    fs.writeFileSync(SHARE_STORE_FILE, JSON.stringify(shareStore))
  } catch (e) {
    console.error('[share] could not persist store:', e.message)
  }
}
function pruneShareStore() {
  const now = Date.now()
  let changed = false
  for (const k of Object.keys(shareStore)) {
    const r = shareStore[k]
    if (r && r.expiresAt && new Date(r.expiresAt).getTime() < now) {
      delete shareStore[k]
      changed = true
    }
  }
  if (changed) saveShareStore()
}

/* Cheap per-IP rate limits (in-memory, reset on restart). */
const rate = { create: {}, resolve: {} }
function rateLimited(bucket, key, max, windowMs) {
  const now = Date.now()
  const arr = (rate[bucket][key] = (rate[bucket][key] || []).filter((t) => now - t < windowMs))
  if (arr.length >= max) return true
  arr.push(now)
  return false
}

/** Only genuine, well-formed Reimagined snapshots are accepted. */
function sanitizeSnapshotShape(snap) {
  if (!snap || typeof snap !== 'object') return null
  if (snap.schema !== 'reimagined-profile') return null
  if (typeof snap.name !== 'string' || !snap.name) return null
  if (typeof snap.minecraftVersion !== 'string' || !snap.minecraftVersion) return null
  if (!Array.isArray(snap.items)) return null
  return snap
}

function genShareCode() {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  let s = ''
  for (let i = 0; i < 11; i++) s += chars[Math.floor(Math.random() * chars.length)]
  return s
}

/** POST /api/share — body { snapshot } → { code, expiresAt }. */
function handleShareCreate(body, req, res) {
  const ip = req.socket.remoteAddress || '?'
  if (rateLimited('create', ip, 15, 60 * 60 * 1000)) {
    res.writeHead(429)
    return res.end(JSON.stringify({ error: 'rate_limited', message: 'Too many codes from this IP — try again later.' }))
  }
  let snap = null
  try {
    const raw = JSON.parse(body.toString('utf8'))
    snap = sanitizeSnapshotShape(raw && raw.snapshot)
  } catch {
    snap = null
  }
  if (!snap) {
    res.writeHead(400)
    return res.end(JSON.stringify({ error: 'invalid_snapshot', message: 'Expected a valid Reimagined profile snapshot.' }))
  }
  loadShareStore()
  pruneShareStore()
  let code = ''
  for (let i = 0; i < 6 && !code; i++) {
    const c = genShareCode()
    if (!shareStore[c]) code = c
  }
  if (!code) {
    res.writeHead(503)
    return res.end(JSON.stringify({ error: 'no_codes', message: 'Could not allocate a code — try again.' }))
  }
  const expiresAt = new Date(Date.now() + SHARE_TTL_MS).toISOString()
  shareStore[code] = { snapshot: snap, expiresAt, createdAt: new Date().toISOString() }
  saveShareStore()
  console.log(`[share] code ${code} created (${snap.name}, ${snap.items.length} items)`)
  res.writeHead(200)
  res.end(JSON.stringify({ code, expiresAt }))
}

/** GET /api/share/:code → { snapshot, expiresAt } | 404 | 410. */
function handleShareResolve(code, req, res) {
  const ip = req.socket.remoteAddress || '?'
  if (rateLimited('resolve', ip, 240, 60 * 60 * 1000)) {
    res.writeHead(429)
    return res.end(JSON.stringify({ error: 'rate_limited', message: 'Too many lookups — try again later.' }))
  }
  loadShareStore()
  const key = String(code || '').trim().toUpperCase()
  const rec = shareStore[key]
  if (!rec) {
    res.writeHead(404)
    return res.end(JSON.stringify({ error: 'not_found', message: 'This share code is invalid or has expired.' }))
  }
  if (rec.expiresAt && new Date(rec.expiresAt).getTime() < Date.now()) {
    delete shareStore[key]
    saveShareStore()
    res.writeHead(410)
    return res.end(JSON.stringify({ error: 'expired', message: 'This share code has expired.' }))
  }
  console.log(`[share] code ${key} resolved (${(rec.snapshot && rec.snapshot.name) || '?'})`)
  res.writeHead(200)
  res.end(JSON.stringify({ snapshot: rec.snapshot, expiresAt: rec.expiresAt }))
}

/** Collect a request body with a hard size cap (protects the free tier). */
function collectBody(req, res, capBytes, done) {
  let size = 0
  const chunks = []
  req.on('data', (d) => {
    size += d.length
    if (size > capBytes) {
      res.writeHead(413)
      res.end(JSON.stringify({ error: 'too_large', message: 'Payload too large.' }))
      req.destroy()
      return
    }
    chunks.push(d)
  })
  req.on('end', () => done(Buffer.concat(chunks)))
  req.on('error', () => done(Buffer.alloc(0)))
}

http.createServer(async (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
  res.setHeader('Content-Type', 'application/json')
  if (req.method === 'OPTIONS') { res.writeHead(204); return res.end() }
  const u = new URL(req.url, 'http://x')
  // /health — liveness for Render's health check and UptimeRobot's pings.
  if (u.pathname === '/health') { res.writeHead(200); return res.end(JSON.stringify({ ok: true })) }
  // / — tiny info page (also useful as a sanity check in a browser).
  if (u.pathname === '/') {
    res.writeHead(200)
    return res.end(JSON.stringify({
      name: 'Reimagined CurseForge proxy + share',
      status: 'ok',
      routes: ROUTES.length + 2,
      share: { create: 'POST /api/share', resolve: 'GET /api/share/:code' }
    }))
  }

  // Share endpoints (v1.0.81) — POST create, GET resolve.
  if (u.pathname === '/api/share' && req.method === 'POST') {
    return collectBody(req, res, MAX_SNAPSHOT_BYTES, (body) => handleShareCreate(body, req, res))
  }
  const shareMatch = u.pathname.match(/^\/api\/share\/([A-Za-z0-9]+)$/)
  if (shareMatch && req.method === 'GET') {
    return handleShareResolve(shareMatch[1], req, res)
  }
  if (u.pathname.startsWith('/api/share')) {
    res.writeHead(405)
    return res.end(JSON.stringify({ error: 'Method not allowed' }))
  }

  if (req.method !== 'GET') { res.writeHead(405); return res.end(JSON.stringify({ error: 'Method not allowed' })) }
  const m = ROUTES.find((r) => r.re.test(u.pathname))
  if (!m) { res.writeHead(404); return res.end(JSON.stringify({ error: 'Not found' })) }
  const out = await proxy(u, m)
  res.writeHead(out.status)
  res.end(typeof out.body === 'string' ? out.body : JSON.stringify(out.body))
}).listen(PORT, () => {
  console.log(`[cf-proxy] listening on :${PORT} — key configured: ${CF_API_KEY.length > 6}, share codes: on`)
})
